export const personnelData = [
  {
    name: "何红阳",
    email: "hongyang.he@woodplc.com", 
    phone: "13000000000",
    department: "金山中心",
    major: "工艺",
    projects: ["空分", "生物乙醇", "PMMA"],
    industries: ["基础化工", "精细化工"],
    regions: [],
    skills: ["设计管理", "项目管理"],
    qualifications: [],
    location: "徐汇"
  },
  {
    name: "朱雪梅",
    email: "xuemei.zhu@woodplc.com",
    phone: "13000000000",
    department: "金山中心", 
    major: "工艺",
    projects: ["特种沥青", "硫磺回收", "MMA"],
    industries: ["石油化工", "基础化工"],
    regions: [],
    skills: ["设计管理", "工程设计"],
    qualifications: [],
    location: "惠州"
  },
  {
    name: "王平",
    email: "ping.wang@woodplc.com",
    phone: "13000000000",
    department: "金山中心",
    major: "结构",
    projects: ["立体仓库", "密闭除焦"],
    industries: ["石油化工", "煤化工"],
    skills: ["工程设计", "设计审查"],
    qualifications: ["一级建造师", "注册结构"],
    regions: [],
    location: "银川"
  },
  {
    name: "王爱民",
    email: "aimin.wang@woodplc.com",
    phone: "13000000000",
    department: "施工部",
    major: "施工管理",
    projects: ["常减压", "加氢", "制氢", "全厂管廊"],
    industries: ["石油化工", "煤化工"],
    skills: ["施工管理"],
    qualifications: [],
    regions: [],
    location: "沈阳"
  },
  {
    name: "徐严勇",
    email: "yanyong.xv@woodplc.com",
    phone: "13000000000",
    department: "施工部",
    major: "安全",
    projects: ["过氧化物", "空分", "合成橡胶"],
    industries: ["基础化工"],
    skills: ["HSE管理"],
    qualifications: [],
    regions: [],
    location: "金山"
  },
  {
    name: "颉晓永",
    email: "xiaoyong.xie@woodplc.com",
    phone: "13000000000",
    department: "施工部",
    major: "质量",
    projects: ["PMMA", "聚烯烃", "LNG", "磷酸盐", "环氧乙烷"],
    industries: ["石油化工", "无机化工"],
    skills: ["质量管理"],
    qualifications: [],
    regions: [],
    location: "湛江"
  },
  {
    name: "戴作滔",
    email: "zuotao.dai@woodplc.com",
    phone: "13000000000",
    department: "仪电室",
    major: "仪表",
    projects: ["锂电池", "PE", "氯碱", "烧碱"],
    industries: ["基础化工", "无机化工"],
    skills: ["软件二次开发", "工程设计"],
    qualifications: [],
    regions: [],
    location: "金山"
  },
  {
    name: "郭超华",
    email: "chaohua.guo@woodplc.com",
    phone: "13000000000",
    department: "仪电室",
    major: "电气",
    projects: ["炼化一体化", "芳烃", "聚酯", "研发中心"],
    industries: ["石油化工", "精细化工"],
    skills: ["工程设计"],
    qualifications: ["注册电气工程师"],
    regions: [],
    location: "金山"
  },
  {
    name: "刘贺南",
    email: "henan.liu@woodplc.com",
    phone: "13000000000",
    department: "仪电室",
    major: "电信",
    projects: ["数字化顶层设计", "全厂电信系统"],
    industries: ["石油化工", "煤化工"],
    skills: ["全厂电信系统", "顶层设计", "工程设计"],
    qualifications: [],
    regions: [],
    location: "未知"
  },
  {
    name: "张三",
    email: "zhangsan@woodplc.com",
    phone: "13000000000",
    department: "仪电室",
    major: "电信",
    projects: ["数字化顶层设计", "全厂电信系统", "智能工厂建设", "工业互联网平台", "工业安全体系", "工业数据中心", "工业云平台", "5G专网建设", "工业大数据", "边缘计算"],
    industries: ["石油化工", "煤化工"],
    skills: ["全厂电  信系统", "顶层设计", "工程设计", "智能工厂规划", "工业互联网", "工业网络安全", "工业控制系统", "工业通信协议", "工业数据采集", "工业云平台", "工业大数据分析"],
    qualifications: [],
    regions: [],
    location: "未知"
  },
]
